### PR TITLE
Add smart alert policy configs for Dataproc Cluster and Job resource

### PR DESCRIPTION
**Pull request by viratbansal**
Cluster - https://screenshot.googleplex.com/vdHjyYxGwaTRruG
Job - https://screenshot.googleplex.com/4mTW5Z76E8Ur74Z

### CODE REVIEW

**Comment by viratbansal** [comment]
All checks have passed now. This PR is ready to review.

**Review by cocosheng — APPROVED** [review]
we highly recommended adding document section to the policy so users are aware of how to resolve the issues.

**Comment by viratbansal** [comment]
> we highly recommended adding document section to the policy so users are aware of how to resolve the issues.

Thanks for the recommendation. For now, we feel that description section of the alert that we add to metadata.yaml file is good enough but this is something we will keep in mind.

**Comment by viratbansal** [comment]
Can we please merge this to GoogleCloudPlatform:master if there are no other comments? @cocosheng

**Pull request merged**
