### PR TITLE
Add 5 log-based alert templates for Cloud Deploy

### PR DESCRIPTION
**Pull request by linjingsde**
Screenshot 2023-10-18 at 10 26 15 AM

### CODE REVIEW

**Review by cocosheng — COMMENTED** [review]
we highly recommend adding some documentation to these templates for a better troubleshooting journey for users.

**Comment by linjingsde** [comment]
> we highly recommend adding some documentation to these templates for a better troubleshooting journey for users.

Hi, this is our first draft of alerts, we want to roll this out to gather user feedback first then we will add our documentation

**Comment by EvanSimpson** [comment]
@ddli-google are you able to take a look?

**Review by ddli-google — APPROVED** [review]

**Comment by ddli-google** [comment]
Sounds good; merged.

**Pull request merged**
